id: AC664B48A
base_file: f9504.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:16:41.370168
  last_modified_at: 2022-06-15 20:16:41.370172
